export enum productsActionTypes {
    FETCH_PRODUCTS = 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE',
    FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT',
    FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS',
    FETCH_SINGLE_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE',
    PAGINATE_DATA = 'PAGINATE_DATA',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE',
    UPDATE_PRODUCT='UPDATE_PRODUCT',
    UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'
}