export enum productsActionTypes {
    FETCH_PRODUCTS = 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE',
    FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT',
    FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS',
    FETCH_SINGLE_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE',
}