export const CartActionTypes = {
    LOAD_CART_PRODUCTS: "LOAD_CART_PRODUCTS",
    ADD_TO_CART: "Add_To_Cart",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
    DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
    SET_QUANTITY: "SET_QUANTITY",
    APPLY_COUPON: "APPLY_COUPON",
    ADD_SHIPPING_COST: "ADD_SHIPPING_COST",
}

